### PR TITLE
allow to pass Site instance as request parameter(duck typing)

### PR DESCRIPTION
**Pull request by armicron**
see my last commit

### CODE REVIEW

**Comment by armicron** [comment]
We can call EmailAddress.change, EmailAddress.send_confirmation and pass the `Site()` instead of `request`.  Those functions don't use `request`, they pass it until `build_absolute_uri()`: 
`EmailAddress.change()`-> `EmailAddress.send_confirmation()`->`EmailConfirmation.send()`-> and finally `build_absolute_uri()`
Reason for this: we don't have `request` in workflows. 
https://github.com/miraculixx/shrebo-ext/blob/pluto-authchange/base/shrbase/shrres/profile/workflow.py#L40

**Comment by miraculixx** [comment]
turns out we still need it, if removed we get the following exception, as you said:

```
AttributeError: 'Site' object has no attribute 'build_absolute_uri'
```

full stack for reference:

```
ERROR: test_update_profile (shrui.test.profile_form.ProfileViewTests)
Sends profile.send_motivational_email and
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/patrick/projects/shrebo-ext/apps/shrui/shrui/test/profile_form.py", line 39, in test_update_profile
    self.get_profile_data())
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/django/test/client.py", line 482, in post
    secure=secure, **extra)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/django/test/client.py", line 296, in post
    secure=secure, **extra)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/django/test/client.py", line 358, in generic
    return self.request(**r)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/django/test/client.py", line 440, in request
    six.reraise(*exc_info)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/patrick/projects/shrebo-ext/apps/shrui/shrui/views/profile.py", line 149, in update_profile
    email=sv.form.cleaned_data['email'])
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/djworkflow/workflow.py", line 283, in send
    sender=None, name=self.wf_signal_name, site_id=site_id, **kwargs)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/djworkflow/workflow.py", line 87, in dispatch
    routing_key=celery_routing_key)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/djworkflow/tasks.py", line 93, in apply_async
    args, kwargs, task_id, producer, link, link_error, **options)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/celery/app/task.py", line 551, in apply_async
    link=link, link_error=link_error, **options)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/djworkflow/tasks.py", line 102, in apply
    args, kwargs, link, link_error, **options)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/celery/app/task.py", line 743, in apply
    request=request, propagate=throw)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/celery/app/trace.py", line 355, in eager_trace_task
    uuid, args, kwargs, request)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/celery/app/trace.py", line 253, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/djworkflow/tasks.py", line 156, in run_task
    result = wf.perform_action(**kwargs)
  File "/home/patrick/projects/shrebo-ext/base/shrbase/shrres/profile/workflow.py", line 40, in perform_action
    email_address.change(subsite, email, confirm=True)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/allauth/account/models.py", line 77, in change
    self.send_confirmation(request)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/allauth/account/models.py", line 58, in send_confirmation
    confirmation.send(request, signup=signup)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/allauth/account/models.py", line 122, in send
    get_adapter(request).send_confirmation_mail(request, self, signup)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/allauth/account/adapter.py", line 383, in send_confirmation_mail
    emailconfirmation)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/allauth/account/adapter.py", line 376, in get_email_confirmation_url
    url)
  File "/home/patrick/.virtualenvs/shrebodemo/local/lib/python2.7/site-packages/allauth/utils.py", line 249, in build_absolute_uri
    uri = request.build_absolute_uri(location)
AttributeError: 'Site' object has no attribute 'build_absolute_uri'
```

**Comment by armicron** [comment]
@miraculixx 
This exception is caused because we provide `Site` instead of `request` (`request` can be None for new versions of django-allauth).

**Comment by miraculixx** [comment]
yes, let me clarify, the above test was to determine and document whether we still need the change introduced in this commit. the result is that we do. issue closed.

**Pull request merged**
